export const TRANSACTION_DEPOSITO_REQUEST = 'TRANSACTION_DEPOSITO_REQUEST';
export const TRANSACTION_DEPOSITO_SUCCESS = 'TRANSACTION_DEPOSITO_SUCCESS';
export const TRANSACTION_DEPOSITO_RESET = 'TRANSACTION_DEPOSITO_RESET';

export const TRANSACTION_WITHDRAWL_REQUEST = 'TRANSACTION_WITHDRAWL_REQUEST';
export const TRANSACTION_WITHDRAWL_SUCCESS = 'TRANSACTION_WITHDRAWL_SUCCESS';
export const TRANSACTION_WITHDRAWL_FAIL = 'TRANSACTION_WITHDRAWL_FAIL';
export const TRANSACTION_WITHDRAWL_RESET = 'TRANSACTION_WITHDRAWL_RESET';

export const TRANSACTION_TRANSFER_REQUEST = 'TRANSACTION_TRANSFER_REQUEST';
export const TRANSACTION_TRANSFER_SUCCESS = 'TRANSACTION_TRANSFER_SUCCESS';
export const TRANSACTION_TRANSFER_FAIL = 'TRANSACTION_TRANSFER_FAIL';
export const TRANSACTION_TRANSFER_RESET = 'TRANSACTION_TRANSFER_RESET';

export const TRANSACTION_SALDO_REQUEST = 'TRANSACTION_SALDO_REQUEST';
export const TRANSACTION_SALDO_SUCCESS = 'TRANSACTION_SALDO_SUCCESS';
export const TRANSACTION_SALDO_FAIL = 'TRANSACTION_SALDO_FAIL';
export const TRANSACTION_SALDO_RESET = 'TRANSACTION_SALDO_RESET';

